=== niitagile/Virtusa_data_Batch31/AdvanceJava/coursedetails.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT course-details (course)+>
<!ELEMENT course (name,duration,marks*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ATTLIST course cid ID #REQUIRED>
<!ATTLIST duration dtype CDATA "day">

=== niitagile/Virtusa_data_Batch31/AdvanceJava/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE course-details SYSTEM "coursedetails.dtd">
<course-details>
<course cid="c1">
<name>Java</name>

<duration dtype="weeks">10</duration>
<marks>50</marks>
<marks>56</marks>
</course>
<course  cid="c2">
<name>Java</name>
<duration>10</duration>
<marks>50</marks>
</course>
</course-details>
